protocols = imap lmtp pop3
disable_plaintext_auth = no
auth_mechanisms = plain login

ssl = required
ssl_cert = <@@SSL_CERT@@
ssl_key  = <@@SSL_KEY@@

mail_location = maildir:/var/vmail/%d/%n/Maildir
mail_uid = @@VMAIL_UID@@
mail_gid = @@VMAIL_GID@@

passdb {
  driver = sql
  args   = /etc/dovecot/dovecot-sql.conf
}
userdb {
  driver = sql
  args   = /etc/dovecot/dovecot-sql.conf
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode  = 0600
    user  = postfix
    group = postfix
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode  = 0660
    user  = postfix
    group = postfix
  }
}

service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

log_path = syslog
auth_verbose = yes
