driver  = mysql
connect = host=localhost dbname=@@DB_NAME@@ user=@@DB_USER@@ password=@@DB_PASS@@

default_pass_scheme = BLF-CRYPT

password_query = \
  SELECT username AS user, password \
  FROM mailbox WHERE username='%u' AND active='1'

user_query = \
  SELECT CONCAT('/var/vmail/', maildir) AS home, \
         @@VMAIL_UID@@ AS uid, @@VMAIL_GID@@ AS gid, \
         CONCAT('*:bytes=', quota) AS quota_rule \
  FROM mailbox WHERE username='%u' AND active='1'

iterate_query = SELECT username AS user FROM mailbox WHERE active='1'
